@rootURL = http://localhost:5149

### GET ALL
GET {{rootURL}}/api/VaultItem/
Accept: application/json

### GET All Categories
GET {{rootURL}}/api/VaultItem/categories
Accept: application/json

### GET All Systems
GET {{rootURL}}/api/VaultItem/systems
Accept: application/json

### GET BY ID
GET {{rootURL}}/api/VaultItem/-1
Accept: application/json
### CREATE NEW
POST {{rootURL}}/api/VaultItem/
Content-Type: application/json
{
  "name": "XBOX Game 2 FTW",
  "purchasePrice": "30",
  "system": "Xbox",
  "category": "Games",
  "completeness": "Disc,Box",
  "priceChartingLoosePrice": 10,
  "priceChartingCompletePrice": 20,
  "priceChartingLastUpdated": "2026-07-07"
}
### UPDATE EXISTING
PUT {{rootURL}}/api/VaultItem/5
Content-Type: application/json
{
  "name": "XBOX Game FTW",
  "purchasePrice": "15",
  "system": "Xbox",
  "category": "Games",
  "completeness": "CIB",
  "priceChartingLoosePrice": 10,
  "priceChartingCompletePrice": 20,
  "priceChartingLastUpdated": "2026-07-07"
}
### DELETE
DELETE {{rootURL}}/api/VaultItem/2
Accept: application/json

### SEARCH
GET {{rootURL}}/api/VaultItem/search?name=upDated
Accept: application/json
###