@rootURL = http://localhost:5149

GET {{rootURL}}/api/VaultItem/
Accept: application/json
###
GET {{rootURL}}/api/VaultItem/-1
Accept: application/json
###
POST {{rootURL}}/api/VaultItem/
Content-Type: application/json
{
  "name": "C64 - Breadbin",
  "category": "Hardware",
  "system": "Commodore 64",
  "year": "1983"
}
###
PUT {{rootURL}}/api/VaultItem/1
Content-Type: application/json
{
  "name": "Updated Vault Item",
  "price": "15"
}
###
DELETE {{rootURL}}/api/VaultItem/2
Accept: application/json

###
GET {{rootURL}}/api/VaultItem/search?name=upDated
Accept: application/json
###