// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RetroVaultWebApp.Data;

#nullable disable

namespace RetroVaultWebApp.Data.Migrations
{
    [DbContext(typeof(RetroVaultWebDbContext))]
    [Migration("20260927153827_AddListItems")]
    partial class AddListItems
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("RetroVaultWebApp.Models.ListItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ListType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ListType", "Name")
                        .IsUnique();

                    b.ToTable("ListItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ListType = "Category",
                            Name = "Hardware",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 2,
                            ListType = "Category",
                            Name = "Peripherals",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 3,
                            ListType = "Category",
                            Name = "Games",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 4,
                            ListType = "Category",
                            Name = "Software",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 5,
                            ListType = "Category",
                            Name = "LP",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 6,
                            ListType = "Category",
                            Name = "Books",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 7,
                            ListType = "Category",
                            Name = "Magazines",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 8,
                            ListType = "Category",
                            Name = "Movies",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 9,
                            ListType = "Category",
                            Name = "Other",
                            SortOrder = 8
                        },
                        new
                        {
                            Id = 10,
                            ListType = "System",
                            Name = "PC",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 11,
                            ListType = "System",
                            Name = "PC Engine/TurboGrafx",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 12,
                            ListType = "System",
                            Name = "Commodore 64/128",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 13,
                            ListType = "System",
                            Name = "Commodore Amiga",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 14,
                            ListType = "System",
                            Name = "Commodore 16/Plus4",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 15,
                            ListType = "System",
                            Name = "Atari 2600",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 16,
                            ListType = "System",
                            Name = "Atari 800XL",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 17,
                            ListType = "System",
                            Name = "Atari 7800",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 18,
                            ListType = "System",
                            Name = "Atari ST",
                            SortOrder = 8
                        },
                        new
                        {
                            Id = 19,
                            ListType = "System",
                            Name = "Xbox",
                            SortOrder = 9
                        },
                        new
                        {
                            Id = 20,
                            ListType = "System",
                            Name = "Xbox 360",
                            SortOrder = 10
                        },
                        new
                        {
                            Id = 21,
                            ListType = "System",
                            Name = "Xbox One",
                            SortOrder = 11
                        },
                        new
                        {
                            Id = 22,
                            ListType = "System",
                            Name = "Game & Watch",
                            SortOrder = 12
                        },
                        new
                        {
                            Id = 23,
                            ListType = "System",
                            Name = "MSX",
                            SortOrder = 13
                        },
                        new
                        {
                            Id = 24,
                            ListType = "System",
                            Name = "Playstation 1",
                            SortOrder = 14
                        },
                        new
                        {
                            Id = 25,
                            ListType = "System",
                            Name = "Playstation 2",
                            SortOrder = 15
                        },
                        new
                        {
                            Id = 26,
                            ListType = "System",
                            Name = "Playstation 3",
                            SortOrder = 16
                        },
                        new
                        {
                            Id = 27,
                            ListType = "System",
                            Name = "Playstation 4",
                            SortOrder = 17
                        },
                        new
                        {
                            Id = 28,
                            ListType = "System",
                            Name = "Playstation Portable (PSP)",
                            SortOrder = 18
                        },
                        new
                        {
                            Id = 29,
                            ListType = "System",
                            Name = "Sega Master System",
                            SortOrder = 19
                        },
                        new
                        {
                            Id = 30,
                            ListType = "System",
                            Name = "Sega Mega Drive",
                            SortOrder = 20
                        },
                        new
                        {
                            Id = 31,
                            ListType = "System",
                            Name = "Sega Genesis",
                            SortOrder = 21
                        },
                        new
                        {
                            Id = 32,
                            ListType = "System",
                            Name = "NES",
                            SortOrder = 22
                        },
                        new
                        {
                            Id = 33,
                            ListType = "System",
                            Name = "Famicom",
                            SortOrder = 23
                        },
                        new
                        {
                            Id = 34,
                            ListType = "System",
                            Name = "SNES",
                            SortOrder = 24
                        },
                        new
                        {
                            Id = 35,
                            ListType = "System",
                            Name = "Super Famicom",
                            SortOrder = 25
                        },
                        new
                        {
                            Id = 36,
                            ListType = "System",
                            Name = "Nintendo 64",
                            SortOrder = 26
                        },
                        new
                        {
                            Id = 37,
                            ListType = "System",
                            Name = "GameBoy",
                            SortOrder = 27
                        },
                        new
                        {
                            Id = 38,
                            ListType = "System",
                            Name = "GameBoy Color",
                            SortOrder = 28
                        },
                        new
                        {
                            Id = 39,
                            ListType = "System",
                            Name = "GameBoy Advance",
                            SortOrder = 29
                        },
                        new
                        {
                            Id = 40,
                            ListType = "System",
                            Name = "Nintendo DS",
                            SortOrder = 30
                        },
                        new
                        {
                            Id = 41,
                            ListType = "System",
                            Name = "Nintendo Switch",
                            SortOrder = 31
                        },
                        new
                        {
                            Id = 42,
                            ListType = "System",
                            Name = "GameCube",
                            SortOrder = 32
                        },
                        new
                        {
                            Id = 43,
                            ListType = "System",
                            Name = "Tandy/Radio Shack",
                            SortOrder = 33
                        },
                        new
                        {
                            Id = 44,
                            ListType = "System",
                            Name = "Evercade",
                            SortOrder = 34
                        },
                        new
                        {
                            Id = 45,
                            ListType = "System",
                            Name = "WII",
                            SortOrder = 35
                        },
                        new
                        {
                            Id = 46,
                            ListType = "System",
                            Name = "Other",
                            SortOrder = 36
                        });
                });

            modelBuilder.Entity("RetroVaultWebApp.Models.Theme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BodyBg")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("BodyColor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("CardBg")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("CardBorderColor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("FooterBg")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MutedColor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NavbarBg")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("NavbarTextColor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryColor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Themes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BodyBg = "#ffffff",
                            BodyColor = "#212529",
                            CardBg = "#ffffff",
                            CardBorderColor = "rgba(0,0,0,0.125)",
                            FooterBg = "#f8f9fa",
                            IsBuiltIn = true,
                            MutedColor = "#6c757d",
                            Name = "Light",
                            NavbarBg = "#0d6efd",
                            NavbarTextColor = "#ffffff",
                            PrimaryColor = "#0d6efd"
                        },
                        new
                        {
                            Id = 2,
                            BodyBg = "#ffffff",
                            BodyColor = "#212529",
                            CardBg = "#ffffff",
                            CardBorderColor = "rgba(0,0,0,0.125)",
                            FooterBg = "#f8f9fa",
                            IsBuiltIn = true,
                            MutedColor = "#6c757d",
                            Name = "Dark",
                            NavbarBg = "#0d6efd",
                            NavbarTextColor = "#ffffff",
                            PrimaryColor = "#0d6efd"
                        });
                });

            modelBuilder.Entity("RetroVaultWebApp.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Alias")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredCurrency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("NOK");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
